sudo: required

language: ruby

services:
  - docker

before_install:
  - git submodule init
  - git submodule update
  - cp spectralworkbench/config/database.yml.example spectralworkbench/config/database.yml
  - cp spectralworkbench/config/config.yml.example spectralworkbench/config/config.yml
  - docker-compose build
  - docker ps -a
  - docker-compose run web bundle install
  - docker-compose run web bundle exec rake db:setup
  - docker-compose run web bundle exec rake db:seed
  - docker-compose run web bundle exec rake jasmine:ci

script:
  - bundle exec rake test
