sudo: required

language: ruby

services:
  - docker

before_install:
  - git submodule init
  - git submodule sync
  - cp spectralworkbench/config/database.yml.example spectralworkbench/config/database.yml
  - cp spectralworkbench/config/config.yml.example spectralworkbench/config/config.yml
  - docker-compose build
  - docker ps -a
  - docker-compose run web bundle exec rake test

script:
  - bundle exec rake test
