sudo: required

services:
  - docker

before_install:
  - cp spectralworkbench/config/database.yml.example spectralworkbench/config/database.yml
  - cp spectralworkbench/config/config.yml.example spectralworkbench/config/config.yml
  - docker-compose build
  - docker-compose run web bundle exec bower install --allow-root
  - docker-compose run web bundle exec rake assets:precompile --trace

script:
  - docker-compose run web bundle exec rake jasmine:ci
